language: node_js
node_js: stable
branchs:
  only:
  - master
addons:
    ssh_known_hosts: ${DEPLOY_HOST}
before_install:
- openssl aes-256-cbc -K $encrypted_62e9ddb2e48f_key -iv $encrypted_62e9ddb2e48f_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

after_success:
- scp -P ${DEPLOY_PORT} -r ./** root@${DEPLOY_HOST}:${DEPLOY_PATH}
- npm install
- pm2 restart toolkit